### ISSUE TITLE
a new type of error

### ISSUE THREAD

**Issue by ospfsg** [moiexpositoalonsolab/grenepipe#46]
Hi 

Runs with samples from single individuals seems to be fine. But Runs of poolseq data run into a crash.

terminal close by himself.

This is my config part for freebayes

```
  # ----------------------------------------------------------------------
  #     freebayes
  # ----------------------------------------------------------------------

  # Used only if settings:calling-tool == freebayes
  # See https://github.com/freebayes/freebayes
  freebayes:

    # Extra parameters for freebayes.
    extra: "-p 40 --use-best-n-alleles 4 --pooled-discrete"

    # Settings for parallelization
    threads: 120
    compress-threads: 2
    chunksize: 100000
```

I attached the log file
