### ISSUE TITLE
another type of error

### ISSUE THREAD

**Issue by ospfsg** [moiexpositoalonsolab/grenepipe#47]
Hi 

After editing the reference genome file, as you suggested,  it worked for individual sample files but there is still a problem with PoolSeq data . It crashed and the terminal closed by himself.  The problem seems to be during the snpcalling

This is my config part for freebayes

```
  # ----------------------------------------------------------------------
  #     freebayes
  # ----------------------------------------------------------------------

  # Used only if settings:calling-tool == freebayes
  # See https://github.com/freebayes/freebayes
  freebayes:

    # Extra parameters for freebayes.
    extra: "-p 40 --use-best-n-alleles 4 --pooled-discrete"

    # Settings for parallelization
    threads: 120
    compress-threads: 2
    chunksize: 100000
```

I attached the log file 

[2024-04-09T151509.566084.snakemake.log](https://github.com/moiexpositoalonsolab/grenepipe/files/14947367/2024-04-09T151509.566084.snakemake.log)

and the two log files that seems to be relevant

log: logs/freebayes/JAVFWQ010000033.1.log

[JAVFWQ010000033.1.log](https://github.com/moiexpositoalonsolab/grenepipe/files/14947385/JAVFWQ010000033.1.log)

log: logs/freebayes/chromosome_1.log

[chromosome_1.log](https://github.com/moiexpositoalonsolab/grenepipe/files/14947397/chromosome_1.log)

thank you again
osp
