### ISSUE TITLE
SLURM No wall time information given

### ISSUE THREAD

**Issue by RvV1979** [moiexpositoalonsolab/grenepipe#54]
Hi Lucas, 
I am running the latest version of grenepipe (v0.13.1) with snakemake 8.15.2 using SLURM using `--executor slurm --profile profiles/slurm` options. The file `profiles/slurm/cluster_config.yaml` includes the following:
```
__default__:
  time: 120 # Default time (minutes). A time limit of zero requests that no time limit be imposed
  mem: 10G # Default memory. A memory size specification of zero grants the job access to all of the memory on each node.
  cpus-per-task: 1
  nodes: 1
  ntasks: 1
```
However, when executing the pipeline I get the following warnings and jobs do not get accepted: 
```
No wall time information given. This might or might not work on your cluster. If not, specify the resource runtime in your rule or as a reasonable default via --default-resources.
No job memory information ('mem_mb' or 'mem_mb_per_cpu') is given - submitting without. This might or might not work on your cluster.
```
It seems the specified default settings are not appropriately transmitted. What may be going wrong? 
Thanks
